CREATE TABLE enrollment_session
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(255)                            NOT NULL,
    year                 INTEGER                                 NOT NULL,
    active               BOOLEAN,
    enrollment_freezed   BOOLEAN,
    modification_freezed BOOLEAN,
    CONSTRAINT pk_enrollment_session PRIMARY KEY (id)
);

ALTER TABLE examination_centre_details ADD COLUMN enrollment_session_id BIGINT NOT NULL;
ALTER TABLE school_details ADD COLUMN enrollment_session_id BIGINT NOT NULL;
ALTER TABLE student ADD COLUMN enrollment_session_id BIGINT NOT NULL;
ALTER TABLE student_marks ADD COLUMN enrollment_session_id BIGINT NOT NULL;
ALTER TABLE subject_details ADD COLUMN enrollment_session_id BIGINT NOT NULL;

ALTER TABLE examination_centre_details ADD CONSTRAINT fk_enrollment FOREIGN KEY (enrollment_session_id) REFERENCES enrollment_session(id) ON DELETE CASCADE;
ALTER TABLE school_details ADD CONSTRAINT fk_enrollment FOREIGN KEY (enrollment_session_id) REFERENCES enrollment_session(id) ON DELETE CASCADE;
ALTER TABLE student ADD CONSTRAINT fk_enrollment FOREIGN KEY (enrollment_session_id) REFERENCES enrollment_session(id) ON DELETE CASCADE;
ALTER TABLE student_marks ADD CONSTRAINT fk_enrollment FOREIGN KEY (enrollment_session_id) REFERENCES enrollment_session(id) ON DELETE CASCADE;
ALTER TABLE subject_details ADD CONSTRAINT fk_enrollment FOREIGN KEY (enrollment_session_id) REFERENCES enrollment_session(id) ON DELETE CASCADE;