CREATE TABLE user_details
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by    VARCHAR(255),
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_by   VARCHAR(255),
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    email         VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    kendra_id     BIGINT,
    user_name     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user_details PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by    VARCHAR(255),
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_by   VARCHAR(255),
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    name          VARCHAR(20)                              NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (id)
);

ALTER TABLE user_details
    ADD CONSTRAINT uc_user_details_email UNIQUE (email);

ALTER TABLE user_details
    ADD CONSTRAINT uc_user_details_user_name UNIQUE (user_name);

ALTER TABLE user_details
    ADD CONSTRAINT FK_USER_DETAILS_ON_KENDRA FOREIGN KEY (kendra_id) REFERENCES vigyan_kendra_details (id) ON DELETE CASCADE;