ALTER TABLE student
DROP COLUMN IF EXISTS roll_number;

ALTER TABLE student
ADD COLUMN IF NOT EXISTS roll VARCHAR(255) NOT NULL;

ALTER TABLE student
ADD COLUMN IF NOT EXISTS num VARCHAR(255) NOT NULL;