CREATE TABLE reporting_details (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	report_key varchar NOT NULL,
	enrollment_year varchar NOT NULL,
	vigyankendra_code varchar NOT NULL,
	vigyankendra_name varchar NOT NULL,
	report_date varchar NOT NULL,
	status varchar NOT NULL,
	CONSTRAINT reporting_pk PRIMARY KEY (id),
	CONSTRAINT reporting_unique UNIQUE (report_key)
);
ALTER TABLE student drop constraint FK_STUDENT_ON_SCHOOL;
ALTER TABLE student drop constraint FK_STUDENT_ON_STUDENT_CLASS;

ALTER TABLE student ADD CONSTRAINT FK_STUDENT_ON_SCHOOL FOREIGN KEY (school_id) REFERENCES school_details (id) ON DELETE CASCADE;

ALTER TABLE student ADD CONSTRAINT FK_STUDENT_ON_STUDENT_CLASS FOREIGN KEY (student_class_id) REFERENCES student_class (id) ON DELETE CASCADE;