--liquibase formatted sql
--changeset vigyanmancha:1
CREATE TABLE vigyan_kendra_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   code VARCHAR(255),
   CONSTRAINT pk_vigyan_kendra_details PRIMARY KEY (id)
);
--rollback drop table vigyan_kendra_details;

--changeset vigyanmancha:2
CREATE TABLE school_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   kendra_id BIGINT,
   exam_centre_id INTEGER,
   CONSTRAINT pk_schooldetails PRIMARY KEY (id)
);
--rollback drop table school_details;

--changeset vigyanmancha:3
CREATE TABLE examination_centre_details (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   school_id BIGINT,
   vigyankendra_id BIGINT,
   CONSTRAINT pk_examinationcentredetails PRIMARY KEY (id)
);

--rollback drop table examination_centre_details;

ALTER TABLE school_details ADD CONSTRAINT FK_SCHOOLDETAILS_ON_EXAM_CENTRE FOREIGN KEY (exam_centre_id) REFERENCES examination_centre_details (id) ON DELETE SET NULL;

ALTER TABLE school_details ADD CONSTRAINT FK_SCHOOLDETAILS_ON_KENDRA FOREIGN KEY (kendra_id) REFERENCES vigyan_kendra_details (id) ON DELETE CASCADE;

ALTER TABLE examination_centre_details ADD CONSTRAINT uc_examinationcentredetails_school UNIQUE (school_id);

ALTER TABLE examination_centre_details ADD CONSTRAINT FK_EXAMINATIONCENTREDETAILS_ON_SCHOOL FOREIGN KEY (school_id) REFERENCES school_details (id) ON DELETE CASCADE;

ALTER TABLE examination_centre_details ADD CONSTRAINT FK_EXAMINATIONCENTREDETAILS_ON_VIGYANKENDRA FOREIGN KEY (vigyankendra_id) REFERENCES vigyan_kendra_details (id) ON DELETE CASCADE;

--changeset vigyanmancha:4
CREATE TABLE subject_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_subject_details PRIMARY KEY (id)
);
--rollback drop table subject_details;

--changeset vigyanmancha:5
CREATE TABLE class_subjects (
   class_id BIGINT NOT NULL,
   subject_id BIGINT NOT NULL,
   CONSTRAINT pk_class_subjects PRIMARY KEY (class_id, subject_id)
);

CREATE TABLE student_class (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_student_class PRIMARY KEY (id)
);

ALTER TABLE class_subjects ADD CONSTRAINT fk_clasub_on_student_class FOREIGN KEY (class_id) REFERENCES student_class (id) ON DELETE CASCADE;

ALTER TABLE class_subjects ADD CONSTRAINT fk_clasub_on_subject_details FOREIGN KEY (subject_id) REFERENCES subject_details (id) ON DELETE CASCADE;
--rollback drop table class_subjects;
--rollback drop table student_class;

--changeset vigyanmancha:6
CREATE TABLE student
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    roll_number      VARCHAR(255),
    school_id        INTEGER,
    vigyan_kendra_id BIGINT,
    student_class_id BIGINT,
    sex              VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_student PRIMARY KEY (id)
);

ALTER TABLE student ADD CONSTRAINT FK_STUDENT_ON_SCHOOL FOREIGN KEY (school_id) REFERENCES school_details (id) ON DELETE SET NULL;

ALTER TABLE student ADD CONSTRAINT FK_STUDENT_ON_STUDENT_CLASS FOREIGN KEY (student_class_id) REFERENCES student_class (id) ON DELETE SET NULL;

ALTER TABLE student ADD CONSTRAINT FK_STUDENT_ON_VIGYAN_KENDRA FOREIGN KEY (vigyan_kendra_id) REFERENCES vigyan_kendra_details (id) ON DELETE CASCADE;
--rollback drop table student;

--changeset vigyanmancha:7
CREATE TABLE student_marks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   marks INTEGER NOT NULL,
   maximum_marks INTEGER NOT NULL,
   student_id BIGINT NOT NULL,
   subject_id BIGINT NOT NULL,
   CONSTRAINT pk_studentmarks PRIMARY KEY (id)
);

ALTER TABLE student_marks ADD CONSTRAINT FK_STUDENTMARKS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE;

ALTER TABLE student_marks ADD CONSTRAINT FK_STUDENTMARKS_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subject_details (id) ON DELETE CASCADE;
--rollback drop table student_marks;
